# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_one', models.CharField(max_length=500)),
                ('h1_paragraph1', models.TextField()),
                ('h1_paragraph2', models.TextField(blank=True)),
                ('h1_paragraph3', models.TextField(blank=True)),
                ('h1_paragraph4', models.TextField(blank=True)),
                ('h1_paragraph5', models.TextField(blank=True)),
                ('heading_two', models.CharField(blank=True, max_length=500)),
                ('h2_paragraph1', models.TextField(blank=True)),
                ('h2_paragraph2', models.TextField(blank=True)),
                ('h2_paragraph3', models.TextField(blank=True)),
                ('h2_paragraph4', models.TextField(blank=True)),
                ('h2_paragraph5', models.TextField(blank=True)),
                ('heading_three', models.CharField(blank=True, max_length=500)),
                ('h3_paragraph1', models.TextField(blank=True)),
                ('h3_paragraph2', models.TextField(blank=True)),
                ('h3_paragraph3', models.TextField(blank=True)),
                ('h3_paragraph4', models.TextField(blank=True)),
                ('h3_paragraph5', models.TextField(blank=True)),
                ('image_one', models.ImageField(blank=True, upload_to='news/news_photos')),
                ('file_one', models.FileField(blank=True, upload_to='news/news_files')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
            ],
        ),
    ]
