# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=500)),
                ('paragragh1', models.TextField(blank=True)),
                ('heading1', models.CharField(max_length=500)),
                ('paragragh2', models.TextField(blank=True)),
                ('paragragh3', models.TextField(blank=True)),
                ('paragragh4', models.TextField(blank=True)),
                ('heading2', models.CharField(max_length=500)),
                ('paragragh5', models.TextField(blank=True)),
                ('paragragh6', models.TextField(blank=True)),
                ('paragragh7', models.TextField(blank=True)),
                ('paragragh8', models.TextField(blank=True)),
                ('paragragh9', models.TextField(blank=True)),
                ('paragragh10', models.TextField(blank=True)),
                ('heading3', models.CharField(max_length=500)),
                ('paragragh11', models.TextField(blank=True)),
                ('paragragh12', models.TextField(blank=True)),
                ('heading4', models.CharField(max_length=500)),
                ('paragragh13', models.CharField(max_length=500)),
                ('heading5', models.CharField(max_length=500)),
                ('paragragh14', models.CharField(max_length=500)),
                ('heading6', models.CharField(max_length=500)),
                ('paragragh15', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=500)),
                ('h1_paragragh1', models.TextField(blank=True)),
                ('h1_paragragh2', models.TextField(blank=True)),
                ('h1_paragragh3', models.TextField(blank=True)),
                ('h1_paragragh4', models.TextField(blank=True)),
                ('h1_paragragh5', models.TextField(blank=True)),
                ('h1_paragragh6', models.TextField(blank=True)),
                ('h1_paragragh7', models.TextField(blank=True)),
                ('heading2', models.CharField(max_length=500)),
                ('h2_paragragh1', models.TextField(blank=True)),
                ('h2_paragragh2', models.TextField(blank=True)),
                ('h2_paragragh3', models.TextField(blank=True)),
                ('h2_paragragh4', models.TextField(blank=True)),
                ('h2_paragragh5', models.TextField(blank=True)),
                ('h2_paragragh6', models.TextField(blank=True)),
                ('h2_paragragh7', models.TextField(blank=True)),
                ('heading3', models.CharField(max_length=500)),
                ('h3_paragragh1', models.TextField(blank=True)),
                ('h3_paragragh2', models.TextField(blank=True)),
                ('h3_paragragh3', models.TextField(blank=True)),
                ('h3_paragragh4', models.TextField(blank=True)),
                ('h3_paragragh5', models.TextField(blank=True)),
                ('h3_paragragh6', models.TextField(blank=True)),
                ('h3_paragragh7', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=500)),
                ('h1_paragragh1', models.TextField(blank=True)),
                ('h1_paragragh2', models.TextField(blank=True)),
                ('h1_paragragh3', models.TextField(blank=True)),
                ('h1_paragragh4', models.TextField(blank=True)),
                ('h1_paragragh5', models.TextField(blank=True)),
                ('h1_paragragh6', models.TextField(blank=True)),
                ('h1_paragragh7', models.TextField(blank=True)),
                ('heading2', models.CharField(max_length=500)),
                ('h2_paragragh1', models.TextField(blank=True)),
                ('h2_paragragh2', models.TextField(blank=True)),
                ('h2_paragragh3', models.TextField(blank=True)),
                ('h2_paragragh4', models.TextField(blank=True)),
                ('h2_paragragh5', models.TextField(blank=True)),
                ('h2_paragragh6', models.TextField(blank=True)),
                ('h2_paragragh7', models.TextField(blank=True)),
                ('heading3', models.CharField(max_length=500)),
                ('h3_paragragh1', models.TextField(blank=True)),
                ('h3_paragragh2', models.TextField(blank=True)),
                ('h3_paragragh3', models.TextField(blank=True)),
                ('h3_paragragh4', models.TextField(blank=True)),
                ('h3_paragragh5', models.TextField(blank=True)),
                ('h3_paragragh6', models.TextField(blank=True)),
                ('h3_paragragh7', models.TextField(blank=True)),
            ],
        ),
    ]
