# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20151228_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
